## Name of the action
name: pipeline-template

## Trigger conditions for the action
on:
  push:
    branches:
      - master
    paths:
      - '{Path-to-consumer}'
      - '{Path-to-pipeline-yml}'
  pull_request:
    branches:
      - master
    paths:
      - '{Path-to-consumer}'
      - '{Path-to-pipeline-yml}'

## Environment variables for the action
env:
  CONTAINER: ${{ secrets.DOCKER_IMAGE_NAME }}
  BUILD_CONTEXT_PATH: ${{ secrets.DOCKER_CONTEXT_PATH }}
  PROJECT_FILE_PATH: ${{ secrets.PROJECT_FILE_PATH }}
  DOCKERFILE_PATH: ${{ secrets.DOCKER_CONTEXT_PATH }}/Dockerfile
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
  DOTNET_CORE_VERSION: 8.0.x

## Jobs that the action runs
jobs:
  build-and-test:
    uses: ./.github/workflow-templates/docker-build-base.yml
    with:
      container: ${{ env.CONTAINER }}
      buildcontextpath: ${{ env.BUILD_CONTEXT_PATH }}
      projectfilepath: ${{ env.PROJECT_FILE_PATH }}
      dockerfilepath: ${{ env.DOCKERFILE_PATH }}
      containerregistry: ${{ env.CONTAINER_REGISTRY }}
      dotnetcoreversion: ${{ env.DOTNET_CORE_VERSION }}
    ## Secrets required for the job
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}